/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "home": [],
    "dashboard": [],
    "user": [],
    "create-user": [],
    "trainees": [],
    "create-trainee": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "security.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
